name: "Tests"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "**.py"
      - "**.toml"
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
    paths:
      - "**.py"
      - "**.toml"

env:
  DISCORD_TOKEN: "a"
  HOST_SERVER_HOST: "127.0.0.1"
  HOST_SERVER_SSH_PORT: "25566"
  HOST_SERVER_USER: "root"
  HOST_SERVER_PASSWORD: "root"
  MC_SERVER_START_CMD: "cd /app && ./run.sh"
  MC_SERVER_ADDRESS: "25565"
  DISCORD_SUPER_USER_ID: "a"
  DEBUG: "0"
  DEBUG_LOGGING: "1"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          context: tests
          tags: somnus-test:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          cache: pip
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.lock

      - name: Start Container
        run: |
          docker run -d -p 25566:22 -p 25565:25565 somnus-test:latest

      - name: Run Tests
        run: |
          pytest
